trigger:
  branches:
    include:
    - main
    - feature/*
    exclude:
    - README.md

pool:
  name: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install express --save
    npm install -g mocha@^10.4.0
    npm install -g chai@^4.3.4
    npm run test
  displayName: 'npm install and test'

- task: Docker@2
  inputs:
    containerRegistry: 'dockerHub'
    repository: 'itsyoussefjabri/azure-devops'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildId)'

- script: |
    npm install -g vercel@latest
  displayName: 'Install Vercel CLI'

- script: |
    vercel pull --yes --environment=production --token $(vercelToken)
  displayName: 'Pull Vercel Environment Information'
  
- script: |
    vercel deploy --prod --token $(vercelToken)
  displayName: 'Deploy Project Artifacts to Vercel'
